name: CD

on:
  push:

jobs:
  build_linux_x86_64_gui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install pip requirements
      run: tools/pcommand install_pip_reqs
    - name: Check build cache
      uses: actions/cache@v3
      with:
        path: |
          .cache
          build/assets
        key: ba-cache-linux-x86-64-gui
    - name: Make a release build
      run: make prefab-gui-release-build
    - name: Upload the build
      uses: actions/upload-artifact@v3
      with:
        name: linux_x86_64_gui
        path: build/prefab/full/linux_x86_64_gui
        retention-days: 1
  build_linux_x86_64_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pip requirements
        run: tools/pcommand install_pip_reqs
      - name: Check build cache
        uses: actions/cache@v3
        with:
          path: |
            .cache
            build/assets
          key: ba-cache-linux-x86-64-server
      - name: Make a release build
        run: |
          make prefab-server-release-build
          cp src/assets/gdata_template/ginfo.json build/prefab/full/linux_x86_64_server/ginfo.json
          cp src/assets/gdata_template/glang.json build/prefab/full/linux_x86_64_server/glang.json
          cp src/assets/gdata_template/gshop.json build/prefab/full/linux_x86_64_server/gshop.json
      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: linux_x86_64_server
          path: build/prefab/full/linux_x86_64_server
          retention-days: 1
  build_windows_x86_gui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install pip requirements
      run: tools/pcommand install_pip_reqs
    - name: Check build cache
      uses: actions/cache@v3
      with:
        path: |
          .cache
          build/assets
        key: ba-cache-windows-x86-gui
    - name: Make a release build
      run: make prefab-windows-x86-gui-release-build
    - name: Upload the build
      uses: actions/upload-artifact@v3
      with:
        name: windows_x86_gui
        path: build/prefab/full/windows_x86_gui
        retention-days: 1
  build_windows_x86_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pip requirements
        run: tools/pcommand install_pip_reqs
      - name: Check build cache
        uses: actions/cache@v3
        with:
          path: |
            .cache
            build/assets
          key: ba-cache-windows-x86-server
      - name: Make a release build
        run: |
          make prefab-windows-x86-server-release-build
          cp src/assets/gdata_template/ginfo.json build/prefab/full/windows_x86_server/ginfo.json
          cp src/assets/gdata_template/glang.json build/prefab/full/windows_x86_server/glang.json
          cp src/assets/gdata_template/gshop.json build/prefab/full/windows_x86_server/gshop.json
      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: windows_x86_server
          path: build/prefab/full/windows_x86_server
          retention-days: 1
